---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2018/11/16 09:11
---


local redisCon = require "resty.redis";
local http = require"resty.http";
local json = require "cjson";
local redisClient = redisCon:new ();
local httpc = http:new();
local ok,error = redisClient:connect("127.0.0.1",6379);

if not ok then
    ngx.say("error ",error);
    return ;
end

function login()
    local data = ngx.req.get_body_data();
    local postargs = ngx.req.get_post_args();
    local res, loginerr = redisClient:hget("luaTest",postargs["username"]);
    if not res then
        ngx.say("failed to get key:luaTest",loginerr);
        return;
    end
    if postargs["token"] == res then
        local returnres1, returnres2 = ngx.location.capture_multi{
            {"/SmartBuild/version",{ method = ngx.HTTP_POST,body = data }},
            {"/SmartBuild/cityLcode",{method = ngx.HTTP_POST,body = data}}
        };

         --发送外网连接
         --local returnres, err = httpc:request_uri("http://127.0.0.1/....",
         --       { method = ngx.HTTP_POST,copy_all_vars = true });

        if returnres1.status ~= 200 or returnres2.status ~= 200 then
            ngx.say("error ",returnres1.status," - error ",returnres2.status);
        else
            local returnres1Json = json.decode(returnres1.body);
            local returnres2Json = json.decode(returnres2.body);
            returnres1Json.data["cityLcode"] = returnres2Json.data.cityLcode;
            returnres1Json.data["cityurl"] = returnres2Json.data.url;
            ngx.say(json.encode(returnres1Json));
        end
    else
        ngx.say("faild");
    end
end

ngx.req.read_body();
login();

